default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 6 } %>

development:
  <<: *default
  database: ecosystem

test:
  <<: *default
  database: ecosystem_test
